{
 "title": "Express-prometheus Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Heap Used vs Heap Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes" },
    { "expr": "nodejs_heap_size_total_bytes" }
   ]
  },
  {
   "title": "CPU process metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])"
    },
    {
     "expr": "rate(process_cpu_system_seconds_total[5m])"
    },
    {
     "expr": "rate(process_cpu_user_seconds_total[5m])"
    }
   ]
  },
  {
   "title": "Container up metric",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(up)/3" }
   ]
  },
  {
   "title": "Express-prometheus 95th percentile SLO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Average request duration Express-prometheus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m])/ rate(http_request_duration_seconds_count[5m])"
    }
   ]
  }
 ]
}